CREATE TABLE `Students` (
`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`Name` VARCHAR( 150 ) NOT NULL ,
`LastName` VARCHAR( 200 ) NOT NULL ,
`DateJoined` DATE NOT NULL ,
`OutstandingBalance` BINARY NOT NULL
) ENGINE = MYISAM COMMENT = 'Main table.';
