CREATE TABLE `Students` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `LastName` VARCHAR(200) NOT NULL,
  `DateJoined` DATE NOT NULL,
  `OutstandingBalance` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID`) ) ENGINE = MyISAM;
